[build]
base = "."
publish = "./dist"
functions = "netlify-functions/"
command = "yarn run build"

[[redirects]]
from = "/*"
to = "/.netlify/functions/render"
status = 200

[[headers]]
for = "/*"

[headers.values]
x-designed-by = "skitsanos, https://github.com/skitsanos"